# Generated by Django 5.2.14 on 2026-05-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Termin'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Niski'), ('M', 'Średni'), ('H', 'Wysoki')], default='M', max_length=1, verbose_name='Priorytet'),
        ),
    ]
